name: assessment
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-130.0.dev

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  realm: ^3.4.1
  fluttertoast: ^8.2.8
  rive: ^0.13.13
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/rive_assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
